
version: '3.5'
services:
  parity-authority-0:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 0
    volumes:
      - data-volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command:
      --config parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.10


  parity-authority-1:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 1
    command:
      --config parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8555:8545
      - 8556:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.11


  parity-authority-2:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 2
    command:
      --config parity/config/authority.toml
      --engine-signer 0x002e28950558fbede1a9675cb113f0bd20912019
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8565:8545
      - 8566:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.12


  parity-authority-3:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 3
    command:
      --config parity/config/authority.toml
      --engine-signer 0x9ffe209ab8224106767d9be36ee9a7bd1e503a7f
      --no-persistent-txqueue
      --fast-unlock
    restart: unless-stopped
    ports:
      - 8575:8545
      - 8576:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.13


  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200

volumes:
  data-volume:
networks:
  app_net:
    name: dockerized_network
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24