/*
DO NOT EDIT THIS FILE!
It is generated by zokrates-code/zoKratesCodeGenerator.js
Edit the template there instead.
*/
pragma solidity ^0.6.1;
/**
* @title Verifier contract interface
*/
interface IVerifier {
  function verifyTx(
    uint[2] calldata a,
    uint[2][2] calldata b,
    uint[2] calldata c,
    uint[8] calldata input) external returns (bool);
}