version: '3'
services:
  household_processing_unit_0:
    build:
      context: .
      dockerfile: household-processing-unit/docker-admin/Dockerfile
    environment:
      - HHS_PORT=3002
    volumes:
      - node0
    ports:
      - 8045:8545
      - 8046:8546
      - 3010:3000
      - 3002:3002
  household_processing_unit_1:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    environment:
      - HHS_PORT=3003
      - PASSWORD=somepass
    ports:
      - 8145:8545
      - 8146:8546
      - 3011:3000
      - 3003:3002
    volumes:
      - node1
    depends_on:
      - household_processing_unit_0
volumes:
  node0:
  node1: