[parity]
chain = "parity/config.json"
base_path = "/tmp/parity-0"
[network]
port = 30300
[rpc]
port = 8540
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["parity/node.pwds"]
[mining]
reseal_on_txs = "none"